// packages/mobile/scripts/generate-registry.ts

import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync, existsSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";

const SITE_URL = process.env.EXPO_PUBLIC_EMDASH_URL;
const BUILD_TOKEN = process.env.EMDASH_BUILD_TOKEN;

if (!SITE_URL) {
	console.error("EXPO_PUBLIC_EMDASH_URL is required");
	process.exit(1);
}
if (!BUILD_TOKEN) {
	console.error("EMDASH_BUILD_TOKEN is required");
	process.exit(1);
}

interface BuildConfig {
	branding: {
		appName: string;
		appSlug: string;
		iosBundle: string;
		androidPackage: string;
		scheme: string;
		splashBgColor: string;
		accentColor: string;
	};
	siteUrl: string;
	plugins: Array<{
		id: string;
		version: string;
		native: boolean;
		entryUrl?: string;
	}>;
}

const DASH_RE = /-/g;

function capitalize(s: string): string {
	return s.charAt(0).toUpperCase() + s.slice(1);
}

async function main() {
	console.log(`Fetching build config from ${SITE_URL}...`);
	const configRes = await fetch(`${SITE_URL}/_emdash/api/app/build-config`, {
		headers: { Authorization: `Bearer ${BUILD_TOKEN}` },
	});
	if (!configRes.ok) {
		console.error(`Failed to fetch build config: ${configRes.status}`);
		process.exit(1);
	}
	const { data: config } = (await configRes.json()) as { data: BuildConfig };

	const mobileDir = resolve(import.meta.dirname, "..");
	const pluginsDir = join(mobileDir, ".plugins");

	// Clean previous plugin extracts
	if (existsSync(pluginsDir)) rmSync(pluginsDir, { recursive: true });
	mkdirSync(pluginsDir, { recursive: true });

	// Download and extract mobile.tgz for marketplace native plugins
	const nativePlugins = config.plugins.filter((p) => p.native);

	for (const plugin of nativePlugins) {
		console.log(`Downloading mobile bundle for ${plugin.id}@${plugin.version}...`);

		// Try to get mobile bundle from site (marketplace plugins store it in R2)
		const bundleUrl = `${SITE_URL}/_emdash/api/plugins/${plugin.id}/mobile-bundle`;
		const res = await fetch(bundleUrl, {
			headers: { Authorization: `Bearer ${BUILD_TOKEN}` },
		});

		if (!res.ok) {
			// Configured plugins don't have downloadable mobile bundles — they're in node_modules
			console.log(`  Skipping download for ${plugin.id} (configured plugin, using workspace)`);
			continue;
		}

		const pluginDir = join(pluginsDir, plugin.id);
		mkdirSync(pluginDir, { recursive: true });

		const tgzPath = join(pluginsDir, `${plugin.id}.tgz`);
		const buffer = Buffer.from(await res.arrayBuffer());
		writeFileSync(tgzPath, buffer);

		// Extract tarball safely using execFileSync (no shell injection)
		execFileSync("tar", ["-xzf", tgzPath, "-C", pluginDir], { stdio: "inherit" });
		rmSync(tgzPath);
		console.log(`  Extracted ${plugin.id} mobile source to ${pluginDir}`);
	}

	// Generate registry.ts
	const imports: string[] = [];
	const spreads: string[] = [];
	const initCases: string[] = [];

	for (const plugin of nativePlugins) {
		const pluginDir = join(pluginsDir, plugin.id);
		const hasExtracted =
			existsSync(pluginDir) &&
			(existsSync(join(pluginDir, "index.ts")) || existsSync(join(pluginDir, "index.js")));
		const alias = plugin.id.replace(DASH_RE, "_");
		const capAlias = capitalize(alias);

		if (hasExtracted) {
			// Marketplace plugin — import from extracted .plugins directory
			imports.push(
				`import { screens as ${alias}Screens, configure${capAlias}Api } from "../.plugins/${plugin.id}/index.js";`,
			);
		} else {
			// Configured plugin — import from node_modules via workspace
			const pkgName = `@emdash-cms/plugin-${plugin.id}`;
			imports.push(
				`import { screens as ${alias}Screens, configure${capAlias}Api } from "${pkgName}/mobile";`,
			);
		}

		spreads.push(`\t...${alias}Screens,`);
		initCases.push(
			`\tif (pluginId === "${plugin.id}") configure${capAlias}Api({ baseUrl, getAuthToken });`,
		);
	}

	const registryContent = `// AUTO-GENERATED by scripts/generate-registry.ts — do not edit manually
import type { ComponentType } from "react";

${imports.join("\n")}

export interface PluginScreenProps {
\ttheme: Record<string, string>;
\tnavigate: (screen: string, params?: Record<string, string>) => void;
\tgoBack: () => void;
\tparams: Record<string, string>;
\tauthToken: string | null;
\trequestLogin: () => Promise<boolean>;
\tupdateCartBadge: (count: number) => void;
}

const screenRegistry: Record<string, ComponentType<PluginScreenProps>> = {
${spreads.join("\n")}
};

export function getScreen(id: string): ComponentType<PluginScreenProps> | undefined {
\treturn screenRegistry[id];
}

export function initializePlugin(
\tpluginId: string,
\tbaseUrl: string,
\tgetAuthToken: () => string | null,
): void {
${initCases.length > 0 ? initCases.join("\n") : "\t// No native plugins to initialize"}
}
`;

	const registryPath = join(mobileDir, "lib", "registry.ts");
	writeFileSync(registryPath, registryContent);
	console.log(`Generated ${registryPath} with ${nativePlugins.length} native plugin(s)`);

	// Write branding env vars for app.config.ts
	const envContent = [
		`APP_NAME=${config.branding.appName}`,
		`APP_SLUG=${config.branding.appSlug}`,
		`APP_IOS_BUNDLE=${config.branding.iosBundle}`,
		`APP_ANDROID_PACKAGE=${config.branding.androidPackage}`,
		`APP_SCHEME=${config.branding.scheme}`,
		`APP_SPLASH_BG=${config.branding.splashBgColor}`,
		`EXPO_PUBLIC_EMDASH_URL=${SITE_URL}`,
	].join("\n");

	writeFileSync(join(mobileDir, ".env.build"), envContent);
	console.log("Generated .env.build with branding config");
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
